version: '2.0'

services:

  elasticsearch-235:
    image: elasticsearch:2.3.5
    networks:
      midomo:
        ipv4_address: 10.10.0.1

  percona:
    image: percona
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=my_database
    networks:
      midomo:
        ipv4_address: 10.10.0.2

  nginx:
    image: nginx
    networks:
      midomo:
        ipv4_address: 10.10.0.3

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOSTS=percona
    networks:
      midomo:
        ipv4_address: 10.10.0.4

networks:
  midomo:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/24
          gateway: 10.10.0.254